apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-load-test
spec:
  parallelism: 1
  script:
    volumeClaim:
      name: graphql-load-test
      readOnly: false
      file: script.js
  arguments: --out csv=/test/results.csv
